# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-13 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=30)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_upd', models.DateTimeField(default=django.utils.timezone.now)),
                ('upd_type', models.CharField(default='', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('can_be_deleted', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('internal_name', models.CharField(max_length=30)),
                ('name', models.CharField(default='Unknown', max_length=30)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_upd', models.DateTimeField(default=django.utils.timezone.now)),
                ('upd_type', models.CharField(default='', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('can_be_deleted', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='FileSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_size', models.IntegerField(default=500)),
                ('cur_size', models.IntegerField(default=0)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=30)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_upd', models.DateTimeField(default=django.utils.timezone.now)),
                ('upd_type', models.CharField(default='', max_length=30)),
                ('bodytext', models.CharField(max_length=150)),
                ('answer_type', models.CharField(max_length=10)),
                ('rate', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionToTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_index_in_test', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=30)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_upd', models.DateTimeField(default=django.utils.timezone.now)),
                ('upd_type', models.CharField(default='', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.Directory')),
            ],
        ),
        migrations.AddField(
            model_name='questiontotest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.Test'),
        ),
        migrations.AddField(
            model_name='directory',
            name='file_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.FileSystem'),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.Directory'),
        ),
    ]
