# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_conductor_app', '0002_auto_20180513_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.Directory'),
        ),
        migrations.AlterField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.Directory'),
        ),
        migrations.AlterField(
            model_name='test',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.Directory'),
        ),
    ]
