# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_conductor_app', '0004_remove_file_internal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
