# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_conductor_app', '0006_auto_20180526_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('is_true', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.File')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_conductor_app.Question')),
            ],
        ),
    ]
