# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_conductor_app', '0007_questionchoices_questionfiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='bodytext',
            new_name='body',
        ),
    ]
