# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_conductor_app', '0008_auto_20180601_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(max_length=20),
        ),
    ]
