# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_conductor_app', '0009_auto_20180601_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
