# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-02 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_conductor_app', '0010_auto_20180601_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystem',
            name='master',
            field=models.IntegerField(),
        ),
    ]
