# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-02 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_conductor_app', '0012_auto_20180602_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesystem',
            old_name='temp_transfer_id',
            new_name='temp_id',
        ),
    ]
